test env file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,6 +29,15 @@ jobs:
       - name: Check Npm -v
         run: npm -v
 
+      - name: Debug secrets.ENV
+        run: |
+          if [[ -z "${{ secrets.ENV }}" ]]; then
+            echo "ERROR: secrets.ENV is empty!"
+            exit 1
+          else
+            echo "secrets.ENV is set but value is hidden for security reasons."
+          fi
+        
 
       # - name: create env file
       #   working-directory: ./
