env file test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,6 +29,15 @@ jobs:
       - name: Check Npm -v
         run: npm -v
 
+      - name: Check ENV secret
+        run: |
+          if [[ -z "${{ secrets.ENV }}" ]]; then
+            echo "ERROR: secrets.ENV is empty!"
+            exit 1
+          fi
+          echo "secrets.ENV is set."
+
+
       - name: create env file
         working-directory: ./
         run: |
